name: Get Data
on:
  schedule:
    - cron: '45 * * * *'
  workflow_dispatch:

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Get cloud data
        run: |
          curl -X GET 'https://clouddata.scratch.mit.edu/logs?projectid=618997313&limit=2&offset=0' -o ./list.json
          
      - name: Get studio host
        run: |
          curl -X GET 'https://api.scratch.mit.edu/studios/5842709/managers?limit=1' -o ./managers.json
        
      - name: Get latest manager thread
        run: |
          curl -X GET 'https://api.scratch.mit.edu/studios/30486213/comments?limit=1' -o ./latestman.json
      
      - name: Get latest curator thread
        run: |
          curl -X GET 'https://api.scratch.mit.edu/studios/30486215/comments?limit=1' -o ./latestcur.json
      
      - name: Get time
        run: |
          TZ=US/Pacific date +{'"date"':'"'%a,' '%I:%M"%p"' '%Z'"'} > time.json
        
      - name: Setup git config
        run: |
          git config user.name "SporkelBot"
          git config user.email ${{ secrets.MY_EMAIL }}
          
      - name: Commit
        run: |
          # Stage the file, commit and push
          git add .
          git diff-index --quiet HEAD || git commit -m "Updated"
          git push
